[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rust_decimal = "1.30"

[build-dependencies]
anyhow = "1.0.71"
convert_case = "0.6.0"
genco = "0.17.7"